require "./spec_helper"

# Man pages generated from the doc: the description becomes NAME and
# DESCRIPTION, the usage section SYNOPSIS, the options OPTIONS.

MAN_DOC = <<-DOC
  Naval Fate.

  Run ships and mines.

  Usage:
    naval_fate ship new <name>...
    naval_fate ship <name> move <x> <y> [--speed=<kn>]
    naval_fate -h | --help

  Options:
    -h --help     Show this screen.
    --speed=<kn>  Speed in knots [default: 10].
  DOC

def man_available? : Bool
  Process.run("sh", ["-c", "command -v groff > /dev/null 2>&1"]).success?
end

describe "Docopt.man_page" do
  it "maps the doc onto the manual sections" do
    page = Docopt.man_page("naval_fate", MAN_DOC, version: "1.0", date: "2026-09-27")
    page.should start_with ".\\\" Generated by docopt.cr"
    page.should contain ".TH NAVAL_FATE 1 \"2026-09-27\" \"naval_fate\" \"1.0\""
    page.should contain "naval_fate \\- Naval Fate."
    page.should contain "naval_fate ship new <name>..."
    page.should contain "[\\-\\-speed=<kn>]"
    page.should contain ".SH DESCRIPTION"
    page.should contain "Run ships and mines."
    page.should contain ".B \\-h, \\-\\-help"
    page.should contain ".B \\-\\-speed <value>"
    page.should contain "Speed in knots. [default: 10]"
  end

  it "guards lines that would start a roff control request" do
    page = Docopt.man_page("prog", "Tool.\n\nUsage:\n  prog\n  .weird\n")
    page.should contain "\\&.weird"
    page.should_not contain "\n.weird"
  end

  it "raises for docs without a usage section" do
    expect_raises(Docopt::DocoptLanguageError) do
      Docopt.man_page("prog", "no usage here")
    end
  end

  if man_available?
    it "renders through groff" do
      with_completion_workdir do |dir|
        page = File.join(dir, "naval_fate.1")
        File.write(page, Docopt.man_page("naval_fate", MAN_DOC, version: "1.0", date: "2026-09-27"))
        status, output, error = run_shell("groff", ["-man", "-Tascii", page])
        plain = output.gsub(/\e\[[0-9;]*m/, "")
        status.should eq 0
        error.should be_empty
        plain.should contain "NAVAL_FATE(1)"
        plain.should contain "Speed in knots"
      end
    end
  end
end
