require "../docopt"

# Man page generation: the doc is the single source of truth, so it
# is also the manual. The description paragraphs become DESCRIPTION,
# the usage section SYNOPSIS and the declared options OPTIONS, in
# roff.

module Docopt
  # Generate a roff man page for *cmd* from its docopt doc.
  #
  # *section* is the manual section (1 by default); *version* and
  # *date* are optional strings for the page footer, so the output is
  # deterministic for tests and builds.
  def self.man_page(cmd : String, doc : String, section : Int32 = 1,
                    version : String? = nil, date : String? = nil) : String
    usage_sections = parse_section("usage:", doc)
    if usage_sections.empty?
      raise DocoptLanguageError.new("\"usage\": (case-insensitive) not found.")
    end

    description = description_of(doc)
    summary = description.lines.map(&.strip).reject(&.empty?).first? || cmd

    String.build do |io|
      io << ".\\\" Generated by docopt.cr\n"
      io << ".TH #{cmd.upcase} #{section} #{(date || "").inspect} "
      io << (version ? "#{cmd.inspect} #{version.inspect}" : "\"\" \"\"") << "\n"

      io << ".SH NAME\n"
      io << "#{roff(cmd)} \\- #{roff(summary)}\n"

      io << ".SH SYNOPSIS\n"
      synopsis = synopsis_lines(usage_sections.first)
      synopsis.each_with_index do |line, index|
        io << roff(line) << "\n"
        io << ".br\n" if index < synopsis.size - 1
      end

      unless description.empty?
        io << ".SH DESCRIPTION\n"
        description.each_line do |line|
          io << (line.strip.empty? ? ".br" : roff(line.strip)) << "\n"
        end
      end

      options = parse_defaults(doc)
      unless options.empty?
        io << ".SH OPTIONS\n"
        options.each do |option|
          io << ".TP\n"
          io << ".B #{roff(option_invocation(option))}\n"
          io << roff(option_description(option)) << "\n"
        end
      end
    end
  end

  # The prose before the usage section.
  private def self.description_of(doc : String) : String
    lines = doc.lines
    usage_index = lines.index(&.downcase.lstrip.starts_with?("usage:")) || lines.size
    lines[0...usage_index].join("\n").rstrip
  end

  # Usage lines without the "usage:" marker on the first one, with
  # continuations left-aligned to it.
  private def self.synopsis_lines(usage_section : String) : Array(String)
    result = [] of String
    usage_section.lines.each_with_index do |line, index|
      content = index == 0 ? line.sub(/^\s*usage:\s*/i, "") : line
      content = content.rstrip.lstrip
      result << content unless content.empty?
    end
    result
  end

  # The option as written in a manual: "-p, --speed <value>".
  private def self.option_invocation(option : Option) : String
    names = [option.short, option.long].compact.join(", ")
    option.argcount > 0 ? "#{names} <value>" : names
  end

  # The option's help text, with the default annotation restated at
  # the end like man pages conventionally do.
  private def self.option_description(option : Option) : String
    description = option.description.gsub(/\s*\[default:\s*[^\]]*\]/i, "").strip
    if option.argcount > 0 && (default = option.value)
      description = "#{description} [default: #{default}]".strip
    end
    description.empty? ? option.long.to_s : description
  end

  # Escape text for roff: backslashes, hyphens, and lines that would
  # start a control request.
  private def self.roff(text : String) : String
    escaped = text.gsub('\\', "\\\\").gsub('-', "\\-")
    escaped = "\\&#{escaped}" if escaped.starts_with?('.') || escaped.starts_with?('\'')
    escaped
  end
end
