require "./completion"

# Fish shell completion generation for docopt
#
# This module provides Fish shell completion functionality by leveraging
# the same parsing infrastructure shared with the bash completion.

module Docopt
  extend self

  class FishCompletion < Completion
    def completion_path : String
      "~/.config/fish/completions"
    end

    def get_completion_filepath(cmd : String) : String
      "#{completion_path}/#{cmd}.fish"
    end

    # When the node's own words are completed: every subcommand along
    # the path must have been seen, and none of this node's
    # subcommands yet (those get their own rules once chosen). Note
    # fish chains conditions with "; and", not a bare "and".
    private def condition_for(path : Array(String), children : Array(String)) : String
      return "__fish_use_subcommand" if path.empty?
      conditions = path.map { |name| "__fish_seen_subcommand_from #{name}" }
      unless children.empty?
        conditions << "not __fish_seen_subcommand_from #{children.join(" ")}"
      end
      conditions.join("; and ")
    end

    private def escape_single_quotes(text : String) : String
      text.gsub("'", "\\'")
    end

    # One rule per declared option, pairing its short and long forms.
    # Options that take a value use -r (require parameter): the rule's
    # -a words then complete the value after "--opt " or "--opt=".
    private def option_rules(cmd : String, path : Array(String), children : Array(String),
                             param_tree : CommandParams, option_help : Hash(String, String)) : Array(String)
      condition = condition_for(path, children)
      param_tree.option_specs.map do |spec|
        String.build do |io|
          io << "complete -c #{cmd}"
          if short_name = spec.short
            io << " -s #{short_name[1]}"
          end
          if long_name = spec.long
            io << " -l #{long_name[2..]}"
          end
          description = description_for(spec.words.first, option_help)
          io << " -d '#{escape_single_quotes(description)}'"
          if spec.takes_value?
            io << " -r"
            if custom = custom_for(spec)
              io << " -a '#{custom}'"
            end
          end
          io << " -n '#{condition}'"
        end
      end
    end

    private def create_rules(cmd : String, path : Array(String), param_tree : CommandParams,
                             option_help : Hash(String, String)) : Array(String)
      rules = [] of String

      unless param_tree.subcommands.empty?
        condition = condition_for(path, param_tree.subcommands.keys)
        rules << "complete -c #{cmd} -f -n '#{condition}' -a '#{param_tree.subcommands.keys.join(" ")}'"
      end

      rules.concat(option_rules(cmd, path, param_tree.subcommands.keys, param_tree, option_help))

      # A custom completion for the whole node completes its
      # positional arguments; without one, fish falls back to its
      # default file completion.
      if custom = @custom_completions[([cmd] + path).join("_")]?
        condition = condition_for(path, [] of String)
        rules << "complete -c #{cmd} -f -n '#{condition}' -a '#{custom}'"
      end

      param_tree.subcommands.each do |subcommand_name, subcommand_tree|
        rules.concat(create_rules(cmd, path + [subcommand_name], subcommand_tree, option_help))
      end
      rules
    end

    def get_completion_file_content(cmd : String, param_tree : CommandParams, option_help : Hash(String, String)) : String
      "# Fish completion for #{cmd}\n# Generated by docopt.cr\n\n#{create_rules(cmd, [] of String, param_tree, option_help).join("\n")}\n"
    end
  end

  def fish_completion(
    cmd : String,
    help : String,
    custom_completions = {} of String => String,
  ) : String
    completion = FishCompletion.new help, custom_completions
    param_tree, option_help = completion.parse_params
    completion.get_completion_file_content(cmd, param_tree, option_help)
  end

  # Completion script for a prebuilt parameter tree, like the one
  # DocTree.read or Dispatch.completion_params produce.
  def fish_completion(
    cmd : String,
    param_tree : CommandParams,
    option_help : Hash(String, String),
    custom_completions = {} of String => String,
  ) : String
    completion = FishCompletion.new nil, custom_completions
    completion.get_completion_file_content(cmd, param_tree, option_help)
  end
end
